name: Test de mon action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Dire bonjour avec mon action
        uses: katycase/nodeCI@main
        with:
          nom: "katycase"
          langue: "es"