name : Deploiement sur Github Pages
on:
  push:
    branches:
      - main

permissions:
    contents: write      

jobs : 
  test_node:
    runs-on : ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Deploy GH
          uses: peaceiris/actions-gh-pages@v3
          with:
             github_token: ${{ secrets.GITHUB_TOKEN}}
             publish_dir: .